is_human_salt: "931158c4979ed5ad247..."
secret_token: "881a29cb89b82bc4a76..."
ga_tracker: "12345"
testing_server: false
privacy_link: "/forums/forums/29/topics/10"
terms_and_conditions_link: "/forums/forums/29/topics/9"
support_category_id: 3
resque_password: "andy"
development:
  host: "localhost:3000"
test:
  host: "localhost:3000"
production:
  host: "lag.tv"